DEFAULT_XLIM = c(-100, 40)
DEFAULT_YLIM = c(-60, 70)

DEFAULT_AXIS_FONT_SIZE = 7

DEFAULT_FILL_COLOR   = "grey"
DEFAULT_BORDER_COLOR = "grey"

DEFAULT_BORDER_LINE_WIDTH = .2

DEFAULT_DARKENING_FACTOR = .2
DEFAULT_AREA_FILL_ALPHA  = .7
